name: Build On PR
on:
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - run: npm run install
      - run: cd server && npm run build
      - run: cd client && npm run build
